import io
import qrcode
from typing import Dict, Any, List
from fastapi.concurrency import run_in_threadpool
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors


class PDFService:
    """Generates PDF prescriptions with ReportLab and embedded QR verification code."""

    @staticmethod
    def _build_prescription_pdf_sync(
        clinic_name: str,
        patient_name: str,
        doctor_name: str,
        diagnosis: str,
        instructions: str,
        exercises: List[Dict[str, Any]],
        prescription_id: str,
    ) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        story = []

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "TitleStyle",
            parent=styles["Heading1"],
            fontSize=20,
            textColor=colors.HexColor("#1E3A8A"),
            alignment=1,
            spaceAfter=12,
        )

        subtitle_style = ParagraphStyle(
            "SubTitleStyle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#4B5563"),
            alignment=1,
            spaceAfter=20,
        )

        header_style = ParagraphStyle(
            "HeaderStyle",
            parent=styles["Heading2"],
            fontSize=12,
            textColor=colors.HexColor("#1F2937"),
            spaceBefore=10,
            spaceAfter=6,
        )

        normal_style = styles["Normal"]

        story.append(Paragraph(clinic_name.upper(), title_style))
        story.append(Paragraph("Physiotherapy & Rehabilitation Prescription", subtitle_style))
        story.append(Spacer(1, 10))

        details_data = [
            [Paragraph(f"<b>Patient Name:</b> {patient_name}", normal_style), Paragraph(f"<b>Prescribing Doctor:</b> {doctor_name}", normal_style)],
            [Paragraph(f"<b>Prescription ID:</b> {prescription_id}", normal_style), Paragraph(f"<b>Diagnosis:</b> {diagnosis}", normal_style)],
        ]
        t_details = Table(details_data, colWidths=[270, 270])
        t_details.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F3F4F6')),
            ('PADDING', (0, 0), (-1, -1), 8),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#D1D5DB')),
        ]))
        story.append(t_details)
        story.append(Spacer(1, 15))

        story.append(Paragraph("Prescribed Exercises & Protocol", header_style))
        exercise_table_data = [["#", "Exercise Title", "Sets", "Reps", "Notes"]]
        for idx, ex in enumerate(exercises, 1):
            exercise_table_data.append([
                str(idx),
                ex.get("title", "Exercise"),
                str(ex.get("sets", 3)),
                str(ex.get("reps", 10)),
                ex.get("notes", "-")
            ])

        t_exercises = Table(exercise_table_data, colWidths=[30, 200, 50, 50, 210])
        t_exercises.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563EB')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB')),
        ]))
        story.append(t_exercises)
        story.append(Spacer(1, 15))

        story.append(Paragraph("Special Instructions", header_style))
        story.append(Paragraph(instructions or "Follow prescribed repetitions. Rest as needed.", normal_style))
        story.append(Spacer(1, 20))

        qr = qrcode.QRCode(version=1, box_size=4, border=1)
        qr.add_data(f"https://physioverse.app/verify/prescription/{prescription_id}")
        qr.make(fit=True)
        img_qr = qr.make_image(fill_color="black", back_color="white")

        qr_buffer = io.BytesIO()
        img_qr.save(qr_buffer, format="PNG")
        qr_buffer.seek(0)

        qr_img = Image(qr_buffer, width=80, height=80)

        footer_table = Table([[qr_img, Paragraph("<b>Scan QR to verify prescription online.</b><br/>Generated by PhysioVerse SaaS Platform", normal_style)]], colWidths=[90, 450])
        footer_table.setStyle(TableStyle([('VALIGN', (0,0), (-1,-1), 'MIDDLE')]))
        story.append(footer_table)

        doc.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes

    @classmethod
    async def generate_prescription_pdf_async(
        cls,
        clinic_name: str,
        patient_name: str,
        doctor_name: str,
        diagnosis: str,
        instructions: str,
        exercises: List[Dict[str, Any]],
        prescription_id: str,
    ) -> bytes:
        """Asynchronously dispatches heavy ReportLab rendering to thread pool worker."""
        return await run_in_threadpool(
            cls._build_prescription_pdf_sync,
            clinic_name=clinic_name,
            patient_name=patient_name,
            doctor_name=doctor_name,
            diagnosis=diagnosis,
            instructions=instructions,
            exercises=exercises,
            prescription_id=prescription_id,
        )
